name: 'news_sentiment'
version: '1.0.0'
config-version: 2

profile: 'news_sentiment'

model-paths: ["models"]

models:
  news_sentiment:
    staging:
      +materialized: view
    marts:
      +materialized: table
